USE [master]
GO

/****** Object:  Database [ProductMgt]    Script Date: 04-01-2021 13:29:38 ******/
CREATE DATABASE [ProductMgt]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ProductMgt', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQL2017\MSSQL\DATA\ProductMgt.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ProductMgt_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQL2017\MSSQL\DATA\ProductMgt_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ProductMgt].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ProductMgt] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ProductMgt] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ProductMgt] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ProductMgt] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ProductMgt] SET ARITHABORT OFF 
GO

ALTER DATABASE [ProductMgt] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ProductMgt] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ProductMgt] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ProductMgt] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ProductMgt] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ProductMgt] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ProductMgt] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ProductMgt] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ProductMgt] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ProductMgt] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ProductMgt] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ProductMgt] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ProductMgt] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ProductMgt] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ProductMgt] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ProductMgt] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ProductMgt] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ProductMgt] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ProductMgt] SET  MULTI_USER 
GO

ALTER DATABASE [ProductMgt] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ProductMgt] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ProductMgt] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ProductMgt] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ProductMgt] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ProductMgt] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ProductMgt] SET  READ_WRITE 
GO


